### ISSUE TITLE
King Model

### ISSUE THREAD

**Issue by jeramkaram** [webbjj/clustertools#4]
Hi there again,
I am wondering if there is a working King density model in clustertools. I have looked over the docs quite a bit and can only find calculations of values such as the concentration for the King model or something like W_0. Is there a way to try and produce a King profile so that I may fit it to my cluster densities? Sorry if this is somewhere in the docs and I just missed it. I greatly appreciate the help.

**Comment by webbjj** [comment]
Hello

clustertools is capable of generating a cluster of stars with positions and velocities drawn from a King density profile. It relies on the limepy software package to do this. However there is no functionality to get a density profile for the King model.

The galpy python software package allows you to easily generate a density profile for a King model, as does the limepy package that clustertools uses. I think galpy also has internal methods that can help you fit the profile to your data.

Hope that helps.

Jeremy

**Comment by jobovy** [comment]
Hi @jeramkaram--Just to follow up on @webbjj's answer, in `galpy` you can do this like this
```
from galpy.df import kingdf
dfk= kingdf(W0=3.,M=2.3,rt=1.76)
print(dfk.dens(1.2))
#0.01659675994295626
```

If you are doing a fit, it might be helpful to use the internal `_scalefreekingdf` class, because the computationally-expensive part of a King profile is solving for the scale-free profile of a given W0, which is done in this class. You can then scale this to any mass or tidal radius. This you would use like
```
from galpy.df.kingdf import _scalefreekingdf
skdf= _scalefreekingdf(3.) # for W0=3
skdf.solve(1001) # 1001=number of points to use to solve for Psi(r)
# Set up scaling to any mass M or tidal radius rt
radius_scale= rt/skdf.rt
mass_scale= M/skdf.mass
velocity_scale= numpy.sqrt(mass_scale/radius_scale)
density_scale= mass_scale/radius_scale**3.
# Compute the density at r
print(skdf.dens(r/radius_scale)*density_scale
```
Note that I haven't run this code, so there might be slight issues, but you can also look at the internals of `kingdf` which this is taken from. If this is useful to you, I might upgrade this internal class to a public interface.

Note that these DF models do not have a way of computing the surface density, but the easiest way to do this is simply to integrate the density from -sqrt(rt**2.-R**2.) to sqrt(rt**2.-R**2.). Also note that there is also a `KingPotential` in `galpy` that allows you to compute the potential, forces, etc. for a King model and this can also compute the surface density, but that just does the numerical integral, so I think it's probably easiest to do it yourself (`KingPotential` uses an interpolated version of the density, so isn't 100% accurate).

**Comment by jeramkaram** [comment]
Thank you both. This is extremely helpful. I've been exploring the galpy github for the last hour or so and there is a lot in there that is extremely useful. Thank you again for the help.
Jeremy
